### ISSUE TITLE
Issues on metadata extraction after last version deployment

### ISSUE THREAD

**Issue by mattiagiupponi** [geosolutions-it/oaw-georectify-process-qgis#19]
Looks like that with the last deployment of the plugin, the metadata are no longer extracted from the images.
In attach logs and warnings  provided by QGIS

[python_warning.txt](https://github.com/geosolutions-it/oaw-georectify-process-qgis/files/7119847/python_warning.txt)

[OAW_plugin_massages.txt](https://github.com/geosolutions-it/oaw-georectify-process-qgis/files/7119848/OAW_plugin_massages.txt)

Example image: 
[test.zip](https://github.com/geosolutions-it/oaw-georectify-process-qgis/files/7119929/test.zip)

**Comment by mattiagiupponi** [comment]
@EddyCatt I made some tests on my local environment ad looks like that there is (probably) so corruption in the files run by the client.
If is possible, I'd like to ask the client to do the following operation to be sure that everything is configured as expected.

**Step 1: Verify that `geotifflib` is at version 1.0.13**
To verify the version is enough to:
- Open QGIS
- Open Python console 
![image](https://user-images.githubusercontent.com/51856725/132350180-fc635302-79a9-4c13-a87d-b9e1e85f8155.png)
- Paste the following code in the console:
```python
import pkg_resources
pkg_resources.get_distribution('geotiflib')
```
- The console will print the version that we need:
![image](https://user-images.githubusercontent.com/51856725/132350901-2164f526-9ce5-4986-bc04-b4fc1af5ad4e.png)

**Step 2: Install test plugin version**
I try to make a patch to the QGIS plugin to see if it fixes. Before release it, I'll like to see if is working as expected.
Ask the client to use this one: [oaw-georectify-process-qgis-test (1).zip](https://github.com/geosolutions-it/oaw-georectify-process-qgis/files/7121795/oaw-georectify-process-qgis-test.1.zip)

**Comment by EddyCatt** [comment]
It seems the Client has a problem with the geotiflib
![geotiflib](https://user-images.githubusercontent.com/86973955/132484058-b9693841-772f-48b4-9da4-65af2e7270a9.png)

**Comment by mattiagiupponi** [comment]
The strange thing is that by themself all the parts are working as expected, but once are merged it raises issues. I'd like to try another approach.

**Step 1: install GIT**
Firstly verify that git is installed on your local machine. To do it open a normal windows terminal and write `git` if a helper like the following is showed, go directly to step 2
```bash
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```
If is not present, please install git via their official website https://git-scm.com/download/win and follow the instructions

**Step 2: install the geotiflib**

Like was already done in the beginning, we need to install the library via console. From the instruction that we send to the client, just follow the same step described in "Installing the dependencies",  and install the library with this command:
```
python.exe -m pip install -U git+https://github.com/geosolutions-it/oaw-georectify-process-alg.git
```
Here is the link to the [DOC](https://docs.google.com/document/d/1px8MAlC--9sZrWJ26aicxFWXxbrDeX-m0v1KE_VHCOA/)

**Step 3 uninstall the QGIS plugin**

Now open QGIS, uninstall the OAW Plugin, and install this package [oaw-georectify-process-qgis-test (3).zip](https://github.com/geosolutions-it/oaw-georectify-process-qgis/files/7128194/oaw-georectify-process-qgis-test.3.zip)
this package is a bit different from the previous one.

If the issue persists, we should find other approaches to the issue

**Comment by EddyCatt** [comment]
OAW say that, after suggested solution, they keep on having the same issue, still no metadata. 
Logs attached (OAW, Pyhton console Python log)

[oaw_log.txt](https://github.com/geosolutions-it/oaw-georectify-process-qgis/files/7129249/oaw_log.txt)
[phyton_console.txt](https://github.com/geosolutions-it/oaw-georectify-process-qgis/files/7129250/phyton_console.txt)
[phyton_log.txt](https://github.com/geosolutions-it/oaw-georectify-process-qgis/files/7129251/phyton_log.txt)

**Comment by mattiagiupponi** [comment]
@EddyCatt The issue is fixed.
In a nutshell, the `HTML` tag converted in the `gdal_edit.py` processes in the `QGIS` app was silently raising an error that was not logged.
With the last changes we introduce:
- Removing the `HTML` conversion from the `QGIS` plugin to Airflow and adding log into a file instead of streaming `PIPE`
- Adding the translation to Airflow and introducing the `OPTIONAL_METADATA` variable which contains the metadata that is optional and they skip the validation

To release the new feature to the client, we should deploy `Airflow` and let the client update his local library.

Following some instructions for the client (when the Airflow deploy will be completed):

**Step 1:** 
update the library by downloading it from the usual link

**Step 2**: clear QGIS cache
To be sure that the installation goes well is usually a good practice to clear the cache. To clean it up just go to:
`Settings` -> `Options` -> `Network`, under the `Cache Settings` tab, just click on the bin

![image](https://user-images.githubusercontent.com/51856725/133267944-10e63fb4-0803-4a0b-9d52-2fc682bc60b0.png)

**Step 3**: uninstall the old library
As a test in the previous emails, we ask to install the library directly to the QGIS python. We were able to install it again through the library, so this is no longer needed. Like was already done in the beginning, just follow the same step described in "Installing the dependencies" and run this command and say "yes" if requested:
```
python.exe -m pip uninstall geotiflib
```
**Step 4**: install QGIS plugin
Uninstall the previous version, restart `QGIS`, install the new version, and restart `QGIS` again.

**Comment by mattiagiupponi** [comment]
@EddyCatt as we saw together, looked like that the issue was raised by the different behaviour of the `gdal_edit` command between **Windows** (qgis) and Ubuntu (airflow).
**Windows** want that in the `subprocess.popen` the `args` must be an `str`, while ubuntu want a `list`
The solution was to add a check to let the script evaluate if the system where is running.
I'm not going to roll back the other feature enabled (`verbose` logs and tag resolution by `airflow`) since are helpful in any case.
